# Generated by Django 4.1.6 on 2023-02-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('loaned', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Sag'), (2, 'Maling'), (3, 'Sveising'), (4, 'Kutt/Kapping'), (5, 'Annet')], default=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
