# Generated by Django 4.1.5 on 2023-02-07 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Saging'), (2, 'Maling'), (3, 'Sveising'), (4, 'Kutt/Kapping'), (5, 'Annet')], default=5, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='loaned',
            field=models.BooleanField(default=False, verbose_name='Utlånt?'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Sted'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Pris'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tittel'),
        ),
    ]
