# Generated by Django 4.1.5 on 2023-03-02 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_alter_listing_category_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Saging'), (2, 'Maling'), (3, 'Sveising'), (4, 'Kutt/Kapping'), (5, 'Skruverktøy'), (6, 'Slagverktøy'), (7, 'Annet')], default=7, verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Startdato')),
                ('end_date', models.DateField(null=True, verbose_name='Sluttdato')),
                ('pending', models.BooleanField(default=True)),
                ('active', models.BooleanField(null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.listing')),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_loaner', to=settings.AUTH_USER_MODEL, verbose_name='Låner')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_owner', to=settings.AUTH_USER_MODEL, verbose_name='Eier')),
            ],
        ),
    ]
