# Generated by Django 4.1.6 on 2023-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_listing_category_alter_listing_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Saging"),
                    (2, "Maling"),
                    (3, "Sveising"),
                    (4, "Kutt/Kapping"),
                    (5, "Skruverktøy"),
                    (6, "Slagverktøy"),
                    (7, "Annet"),
                ],
                default=7,
                verbose_name="Kategori",
            ),
        ),
    ]
