# Generated by Django 4.1.5 on 2023-03-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_listing_category_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='active',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='start_date',
        ),
    ]
