# Generated by Django 4.1.5 on 2023-03-02 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_agreement_active_remove_agreement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Sluttdato'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Startdato'),
        ),
    ]
