# Generated by Django 4.1.5 on 2023-03-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_agreementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementrequest',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_req_listing', to='homepage.listing'),
        ),
    ]
