# Generated by Django 4.1.5 on 2023-03-06 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_agreementrequest_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='pending',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Startdato'),
        ),
    ]
