# Generated by Django 4.1.6 on 2023-03-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_listing_category'),
        ('homepage', '0008_alter_agreementrequest_listing'),
    ]

    operations = [
    ]
