# Generated by Django 4.1.5 on 2023-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_agreement_pending_alter_agreement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Startdato'),
        ),
    ]
