# Generated by Django 4.1.5 on 2023-03-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_agreement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_listing', to='homepage.listing'),
        ),
    ]
