# Generated by Django 4.1.7 on 2023-03-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0010_alter_listing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=50, verbose_name='navn')),
                ('annonser', models.ManyToManyField(to='homepage.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_owner', to=settings.AUTH_USER_MODEL, verbose_name='Eier')),
            ],
        ),
    ]
