# Generated by Django 4.1.5 on 2023-03-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_listing_price'),
        ('homepage', '0011_alter_agreement_listing'),
    ]

    operations = [
    ]
