# Generated by Django 4.1.6 on 2023-03-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_userdefinedlist"),
        ("homepage", "0012_merge_20230306_1540"),
    ]

    operations = []
