# Generated by Django 4.1.7 on 2023-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_userdefinedlist'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userLists',
            field=models.ManyToManyField(to='homepage.userdefinedlist'),
        ),
    ]
