# Generated by Django 4.1.6 on 2023-03-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_userlists_profile_userlists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="userLists",
        ),
    ]
