# Generated by Django 4.1.7 on 2023-03-09 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_userlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tlf',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Telefonnummer'),
        ),
    ]
